### ISSUE TITLE
Error with fit() when using README reproducible example

### ISSUE THREAD

**Issue by bonddr** [business-science/modeltime.gluonts#38]
I have the latest version of R and successfully installed the packages in the deepAR example. I run into a problem when fitting the model:

# Fit a GluonTS DeepAR Model
model_fit_deepar <- deep_ar(
    id                    = "id",
    freq                  = "M",
    prediction_length     = 24,
    lookback_length       = 48,
    epochs                = 5
) %>%
    set_engine("gluonts_deepar") %>%
    fit(value ~ ., training(m750_splits))
    
   I get the following error:
   
   Error in pkg.env$gluonts$mx$distribution$student_t$StudentTOutput() : attempt to apply non-function
   
Any clue on why this is happening?

**Comment by mdancho84** [comment]
This is happening because in GluonTS >= 0.8.0 they have moved the StudentTOutput() function. So please make sure to upgrade your GluonTS by following the [installation instructions here](https://business-science.github.io/modeltime.gluonts/articles/managing-envs.html). You may need to install a "fresh" version of gluonts.

**Comment by bonddr** [comment]
> This is happening because in GluonTS >= 0.8.0 they have moved the StudentTOutput() function. So please make sure to upgrade your GluonTS by following the [installation instructions here](https://business-science.github.io/modeltime.gluonts/articles/managing-envs.html). You may need to install a "fresh" version of gluonts.

This worked - thank you!
