### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'train_dataloader'

### ISSUE THREAD

**Issue by jfergus73** [business-science/modeltime.gluonts#43]
Hello Matt, i’ve been having this issue running “torch” in lab 60, 
![Screen Shot 2022-05-04 at 12 12 45 PM](https://user-images.githubusercontent.com/20796883/166836073-c03251e8-4c0a-4c50-a179-96d5bd13e3ae.png)
I don't know what to do, I've uninstall gluonts, and reinstalled and still the error.

**Comment by MacVoil** [comment]
Hello Matt, I'm getting the same error on windows

![image](https://user-images.githubusercontent.com/105028296/167053246-46aee970-eac4-4273-a2a6-e8348f0e50dc.png)

**Comment by mdancho84** [comment]
I'll have to take a look when I have some free time.

**Comment by mdancho84** [comment]
Here is a solution from another student in the course:

Hello @Matt Dancho and @Juan Fergusson

I was having the same error but, I was able to run deepar with torch by creating a custom env like this

``` r
reticulate::py_install(
    envname  = "my_gluonts_torch_env",
    python_version = "3.7",
    packages = c(
        "mxnet~=1.7",
        "gluonts==0.8.0",
        "pandas==1.0.5",
        "numpy",
        "ujson==4.0.2"
    ),
    method = "conda",
    pip = TRUE
)

torch_pkgs <- c(
    "torch~=1.6",
    "pytorch-lightning==1.5.0"
)

reticulate::py_install(
    packages       = torch_pkgs,
    envname        = "my_gluonts_torch_env",
    method         = "conda",
    pip            = TRUE
)
```

For me the problem was the default version of pytorch-lightning that  install_gluonts() installs in my pc (pytorch-lightning 1.6.3)  when I created the custom env with "pytorch-lightning==1.5.0" I was able to run the model.

I hope this works for you @Juan Fergusson

**Comment by jfergus73** [comment]
Hey Camilo muchas gracias, excelente!!
Hey Matt, did what Camilo suggested and works just fine, thanks a lot …

**Comment by mdancho84** [comment]
Excellent!!
